export const url = {
  bundleIcon: "images/contact/Bundle_icon.svg",
  freeStrawICon: "images/contact/Free_straw_icon.svg",
  joinUsIcon: "images/contact/Join_us_icon.svg",
  referralIcon: "images/contact/Referral_icon.svg",
  filterSortIcon: "images/Filter_sort_icon.svg",
  dropdownIcon: "images/Dropdown_icon.svg",
  arrowLeftIcon: "images/Arrow_left_icon.svg",
  arrowRightIcon: "images/Arrow_right_icon.svg",
  celendarIcon: "images/celendar.svg",
  editIcon : "images/Edit_icon.svg",
  deleteIconGrey : "images/Delete_icon_grey.svg",
  freeShippingIcon : "images/Free_shipping_icon.svg",
  bundleDealIcon: "images/contact/Bundle_deal_icon.svg",
  replacementIcon: "images/contact/Replacement_icon.svg",
  signUpNowIcon: "images/contact/Sign_up_now_icon.svg",
};
